# Generated by Django 4.2.3 on 2023-07-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_raiting_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актер и режиссер', 'verbose_name_plural': 'Актеры и режиссеры'},
        ),
        migrations.RemoveField(
            model_name='actor',
            name='url',
        ),
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(default=1, upload_to='movie_shots/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
