# Generated by Django 4.2.3 on 2023-08-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_actor_description_en_actor_description_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='slug',
        ),
    ]
